# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i -g @nestjs/cli
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run prisma:generate
      - npm run prisma:migrate
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - src/constants/**/*