version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=reswaps
      - POSTGRES_PASSWORD=remora3672
      - POSTGRES_DB=reswaps
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres: